project_id = "hfrsaqfflwvdbywgixxv"

[functions.generate-identity]
verify_jwt = false

[functions.generate-campaign]
verify_jwt = false

[functions.generate-product-ideas]
verify_jwt = false

[functions.generate-logos]
verify_jwt = false

[functions.claim-onboarding]
verify_jwt = true

[functions.generate-product-asset]
verify_jwt = true