project_id = "hfrsaqfflwvdbywgixxv"

[functions.generate-identity]
verify_jwt = false

[functions.generate-campaign]
verify_jwt = false

[functions.generate-product-ideas]
verify_jwt = false

[functions.generate-logos]
verify_jwt = false

[functions.generate-names]
verify_jwt = false

[functions.migrate-onboarding-to-user]
verify_jwt = false

[functions.generate-campaign-concepts]
verify_jwt = false

[functions.generate-product-concepts]
verify_jwt = false

[functions.social-post-tools]
verify_jwt = true

[functions.profile-assist]
verify_jwt = true

[functions.new-message]
verify_jwt = false

[functions.reply-message]
verify_jwt = true

[functions.new-review]
verify_jwt = false

[functions.confirm-review]
verify_jwt = false

[functions.review-reply]
verify_jwt = true

[functions.track-analytics]
verify_jwt = false

[functions.create-starter-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-connect-link]
verify_jwt = true

[functions.stripe-check-capabilities]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true