// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfrsaqfflwvdbywgixxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcnNhcWZmbHd2ZGJ5d2dpeHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDc0NTYsImV4cCI6MjA3NDY4MzQ1Nn0.5yEPvT4Gwxns5BzonLMWWJFygvP8sdD8Wg_6fblZJ60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});